// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgmjbtdlhhusdyavncie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnbWpidGRsaGh1c2R5YXZuY2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODM0MzQsImV4cCI6MjA2Mzc1OTQzNH0.mtjp6WpqWVkSMk5bMlhGA2vjaSx_dbJwSw93pigTAVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);